apiVersion: v1
kind: Secret
metadata:
  name: common-users-secret
type: Opaque
stringData:
  ConnectionStrings__UsersDbConnection: "${DB_CONNECTIONSTRING}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
