apiVersion: v1
kind: Secret
metadata:
  name: common-users-secret
type: Opaque
stringData:
  ConnectionStrings__UsersDbConnection: "${DB_CONNECTIONSTRING}"
  ElasticLogs__ApiKey: "${ELASTIC_LOGS_API_KEY}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
  Jwt__Key: "${JWT_KEY}"
