apiVersion: v1
kind: Secret
metadata:
  name: agro-users-secret
type: Opaque
stringData:
  ConnectionStrings__AgroUsersDbConnection: "${AGRODB_CONNECTIONSTRING}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
